// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kmpgbbgatikmuxivpoxu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImttcGdiYmdhdGlrbXV4aXZwb3h1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMjgwNDEsImV4cCI6MjA2MzYwNDA0MX0.qlnv55vv7uurQmjFaSo__JGoHyxCaJCg55S_BRVoQmQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);